ins=struct();
%% Misc -------------------------------------------------------------------
ins.misc=struct();
ins.misc.mouse = [...
    'Maustaste drücken, um anzufangen'...
    ];
ins.misc.continue = [...
    'Maustaste drücken, um fortzufahren'...
    ];
ins.misc.finished = [...
    'Fertig!'...
    ];
ins.misc.welldone = [...
    'Gut gemacht!'...
    ];
ins.misc.ex_finished = [...
    'Beispielaufgabe fertig!'...
    ];
ins.misc.start = [...
    'DIE AUFGABE BEGINNT!'...
    ];
%ins.misc.e_start = [...
ins.misc.e_start = [...
    'DAS BEISPIEL BEGINNT!'...
    ];

%% Resting ----------------------------------------------------------------
ins.resting=struct();
ins.resting.inst = [...
    'Experiment: Ruhe EEG' ...
    '\n\n\nIm Folgenden sehen Sie ein Kreuz in der Mitte des Bildschirms. '...
    '\n\nFokussieren Sie Ihren Blick auf dieses Kreuz. \nÖffnen und schliessen Sie Ihre Augen,\nwenn Sie dazu aufgefordert werden.'...
    ];
ins.resting.end = [...
    'Nun folgen weitere Aufgaben. '...
    ];

%% Sequence Learning ------------------------------------------------------
ins.seq=struct();
ins.seq.e_inst = [...
    'Experiment: Reihenfolge-Lernen (Übungsaufgabe)' ...
    '\n\n\nIm Folgenden werden Sie 4 Punkte sehen, die in einem' ...
    '\nKreis angeordnet sind. ' ...
    '\n\nDie Punkte leuchten in einer bestimmten Reihenfolge auf. ' ...
    '\nMerken Sie sich die Reihenfolge. Ihre Aufgabe ist es '...
    '\ndie Reihenfolge wiederzugeben. '...
    '\nSie werden die gleiche Reihenfolge mehrmals sehen und ' ...
    '\nhaben somit die Möglichkeit die Reihenfolge zu lernen.' ...
    '\n\nFokussieren Sie Ihren Blick auf das Kreuz in der Mitte. '...
    '\n\nMit der rechten Maustaste können Sie Ihre Eingabe korrigieren.'...
    ];

ins.seq.inst = [...
     'Experiment: Reihenfolge-Lernen' ...
    '\n\n\nDie gleiche Aufgabe wie eben. '...
    '\n\nAber diesmal wird die Reihefolge 8 Einheiten lang sein. '...
    '\n\nSie werden die gleiche Reihenfolge mehrmals sehen und ' ...
    '\nhaben somit die Möglichkeit die Reihenfolge zu lernen. ' ...
    '\n\nFokussieren Sie Ihren Blick auf das Kreuz in der Mitte. '...
    '\n\nMit der rechten Maustaste können Sie Ihre Eingabe korrigieren.'...
    ];
ins.seq.round = [...
    'RUNDE '...
    ];
ins.seq.endround = [...
    'Ende der Runde'...
    ];
ins.seq.repeatseq = [...
    'Wiederholen Sie die Reihenfolge mit der Maus. '...
    ];
ins.seq.ifunknown = [...
    'Falls Sie die genaue Reihenfolge nicht kennen, raten Sie.'...
    ];
ins.seq.endexample = [...
    'Ende des Beispiels'...
    ];
ins.seq.endseq = [...
    'Ende dieser Reihenfolge'...
    ];
ins.seq.endtask = [...
    'Ende der Aufgabe'...
    ];
ins.seq.nextroundmouse = [...
    'Maustaste drücken, um die nächste Runde zu starten. '...
    ];

ins.seq.LTrecallStart = [...
    'Experiment: Reihenfolge-Lernen' ...
    '\n\nVor einigen Minuten haben Sie eine Reihenfolge'...
    '\nvon aufleuchtenden Punkten gelernt.'...
    '\n\nBitte versuchen Sie nun, die ZULETZT erlernte'...
    '\nReihenfolge so gut wie möglich wiederzugeben.'...
    '\n\n Drücken Sie eine Maustaste um zu starten'...
    ];
ins.seq.LTrecallEnd = [...
    'Vielen Dank! Gleich geht es weiter. '...
    ];

%% Processing Speed ------------------------------------------------------
ins.proc=struct();
ins.proc.e_inst = [...
    'Experiment: Symbole Suchen (Übungsaufgabe) '...
    '\n\nIhre Aufgabe ist es herauszufinden, ob eines der ersten'...
    '\nzwei Symbole nochmals auf der gleichen Linie präsentiert wird. '...
    '\n\nWählen Sie mit der linken Maustaste die JA und NEIN Kästchen aus,'...
    '\num Ihre Antwort abzugeben. '...
    '\n\nWenn Sie einen Fehler machen, können Sie Ihre Antwort durch anklicken'...
    '\nder jeweils anderen Box korrigieren. '...
    '\n\nProbieren Sie es hier an einem Beispiel: '...
    ];
ins.proc.e_arrow = [...
    'Vergessen Sie nicht mit dem Pfeil zur nächsten Seite zu gelangen'...
    ];
ins.proc.e_none = [...
    'Keine Antworten erkannt, haben Sie alle Linien beantwortet? '...
    ];
ins.proc.inst = [...
    'Experiment: Symbole Suchen '...
    '\n\n\nDie gleiche Aufgabe wie vorhin. '...
    '\n\nSie haben jetzt 2 Minuten Zeit, um so viele Linien '...
    '\nwie möglich zu bearbeiten. '...
    '\nVersuchen Sie so schnell und so genau wie möglich'...
    '\nzu antworten. '...
    '\n\nVergessen Sie nicht nach Abschluss einer Seite '...
    '\ndurch Klicken des Pfeiles zur nächsten Seite zu gelangen. '...
    '\n\nStellen Sie sicher, dass Sie alle Linien ausgefüllt haben,'...
    '\nbevor Sie zur nächsten Seite fortschreiten. '...
    ];
ins.proc.timeup = [...
    'DIE ZEIT IST UM'...
    ];
ins.proc.none1 = [...
    'Bitte vergewissern Sie sich, dass bei allen Linien eine '...
    ];
ins.proc.none2 = [...
    'Antwort gegeben wurde, bevor Sie zur nächsten Seite fortfahren.'...
    ];

%% Surround Suppression ------------------------------------------------------
ins.surs=struct();
ins.surs.inst = [...
    'Experiment: Visuelle Stimulation '...
    '\n\n\nFokussieren Sie ihren Blick auf den weissen Punkt \nin der Mitte des Bildschirms. '...
    ];
ins.surs.of = [...
    ' von '...
    ];

%% Contrast Change ------------------------------------------------------
ins.cont=struct();
ins.cont.e_title = [...
    'Beispielaufgabe'...
    ];
ins.cont.title = [...
    'Die gleiche Aufgabe wie zuvor, nur mit mehreren Durchgängen'];
ins.cont.inst = [...
    'Konzentrieren Sie sich auf den weissen Punkt in der Mitte des Bildschirms'...
    '\nSie werden Muster sehen, die sich in zufälligen Abständen stärker nach RECHTS oder LINKS neigen werden. '...
    '\n\nDrücken Sie die RECHTE Maustaste, wenn die Linien des Musters eher nach rechts ansteigen'...
    '\n\nDrücken Sie die LINKE Maustaste, wenn die Linien des Musters eher nach links ansteigen'...
    '\n\nWenn das Muster vollständig eine Form erreicht hat, erscheint ein Feedback, ob '...
    '\nein vorhergegangener Klick richtig oder falsch war.'...
    '\n\nVersuchen Sie so schnell wie möglich und so genau wie möglich zu antworten'...
    ];
ins.cont.e_dur = [...
    'Die Beispielaufgabe wird 5 Musterwechsel umfassen'...
    ];
ins.cont.dur = [...
    'Die gesamte Aufgabe dauert 3 Minuten.'...
    ];
ins.cont.ex = [...
    'Beispiel:'...
    ];
ins.cont.left = [...
    'Links'...
    ];
ins.cont.right = [...
    'Rechts'...
    ];

%% Antisaccade ------------------------------------------------------
ins.anti=struct();
ins.anti.e_ins_p = [...
            'Experiment: Prosakkade-Aufgabe (Übungsaufgabe) '...
            '\n\nIm Folgeden werden Sie einen Punkt in der Mitte des '...
            '\nBildschirms sehen. '...
            '\nSobald ein neuer Punkt links oder rechts erscheint, '...
            '\nschauen Sie diesen so schnell wie möglich an.'...
            '\n\nIm Beispiel wird Ihnen Rückmeldung gegeben.'...
            '\nFärbt sich der Mittelpunkt grün bedeutet das,'...
            '\ndass Sie den Punkt richtig angeschaut haben.'...
            '\nDiese Rückmeldung wird in der eigentlichen Aufgabe nicht '...
            '\nmehr gegeben.'...
            ];
ins.anti.e_ins_a = [...
            'Experiment: Antisakkade-Aufgabe (Übungsaufgabe) '....
            '\n\nIm Folgeden werden Sie einen Punkt in der Mitte des '...
            '\nBildschirms sehen. '...
            '\nSobald ein neuer Punkt links oder rechts erscheint, '...
            '\nschauen Sie dieses mal so schnell wie möglich auf die '...
            '\n\nGEGENSEITE.'...
            '\n\nIm Beispiel wird Ihnen Rückmeldung gegeben.'...
            '\nFärbt sich der Mittelpunkt grün bedeutet das,'...
            '\ndass Sie den Punkt richtig angeschaut haben.'...
            '\nDiese Rückmeldung wird in der eigentlichen Aufgabe nicht '...
            '\nmehr gegeben.'...
            ];
ins.anti.e_end = [...
    'Gut gemacht, Ende des Beispiels'...
    ];
ins.anti.e_end2 = [...
    'Gut gemacht, Nun ein Beispiel der anderen Aufgabe'];
ins.anti.break = [...
    'Pause für  '...
    ];

ins.anti.ins_p = [...
            'Experiment: Prosakkade-Aufgabe '...
            '\n\n\nSchauen Sie so schnell wie möglich auf den Punkt'...
            '\nder links oder rechts erscheint. '...
            '\n\n\nEs wird keine Rückmeldung mehr geben.'...
            ];
ins.anti.ins_a = [...
           'Experiment: Antisakkade-Aufgabe '...
            '\n\n\nSchauen Sie so schnell wie möglich zur '...
            '\n\nGEGENSEITE '...
            '\n\ndes Punktes, der links oder rechts erscheint. '...
            '\n\n\nEs wird keine Rückmeldung mehr geben.'...
            ];

ins.anti.end = [...
    'Gut gemacht, Fertig'...
    ];
ins.anti.end2 = [...
    'Gut gemacht, Pause für eine Minute'...
    ];

%% Simple Span

ins.sisp.load = [...
	''...
];
	
ins.sisp.gen_ins =[...
     'Experiment: Gedächtnis-Aufgabe (Übungsaufgabe)'...
	'\n\nIn dieser Aufgabe werden Sie verschiedene Bilder sehen. '...
	'\nIhre Aufgabe ist es, sich die Bilder in der '...
    '\ndargebotenen Reihenfolge einzuprägen.'...
	'\n\nNachdem die Bilder präsentiert wurden, sollen Sie diese '...
	'\naus einer Auswahl an Bildern wiedererkennen. '...
	'\n\nWählen Sie die korrekten Bilder in derselben Reihenfolge '...
	'\nder Präsentation mit der linken Maustaste aus.'...
	'\n\nFixieren Sie während der Präsentation das Kreuz '...
    '\nin der Mitte und versuchen Sie innerliches'...
    '\nbzw leises Nachsprechen der Bilder zu vermeiden. '...
	'\n\nDrücken Sie eine Maustaste,'...
    '\num mit einem Übungsdurchgang zu beginnen.'... 
   
];

ins.sisp.gen_ins2 =[...
     'Experiment: Gedächtnis-Aufgabe.'...
	'\n\nIhre Aufgabe ist dieselbe wie zuvor.'...
    '\nMerken Sie sich die Bilder und versuchen Sie'...
    '\nsie in derselben Reihenfolge wiederzugeben.'... 
	'\n\nFixieren Sie während der Präsentation das Kreuz '...
    '\nin der Mitte und versuchen Sie innerliches'...
    '\n bzw. leises Nachsprechen der Bilder zu vermeiden. '...
	'\n\nDrücken Sie eine Maustaste,'...
    '\num die Aufgabe zu beginnen.'... 
   
];

ins.sisp.picStart =[...
	'Die Bilder starten in: '
];

ins.sisp.recall_ins =[...
     'Bitte wählen Sie nun die Bilder in der präsentierten Reihenfolge aus.'...
	'\nSie können Ihre Antworten mit der rechten Maustaste korrigieren.' ...
	'\nDrücken Sie den unteren Button, um Ihre Antwort abzuschliessen.'...
];

ins.sisp.submit_fail=[...
	'Bitte wählen Sie zuerst 6 Items aus. '...
];

ins.sisp.testSeq_end= [...
    '\n\nDie Übung ist nun vorbei.'...
    '\nGleich beginnt die richtige Aufgabe.'...
	'\nIhre Aufgabe ist dieselbe wie zuvor.'...
	'\nDrücken Sie die linke Maustaste, um fortzufahren.'...	
];

ins.sisp.testSeq_fail= [...
	'Sie sollten mindestens 3 Bilder korrekt auswählen,'...
    '\nbitte versuchen Sie es erneut.'...
	'\nDrücken Sie die linke Maustaste, um fortzufahren. '...
];

ins.sisp.trialEnd = [...
	'Drücken Sie die linke Maustaste, um fortzufahren. '...
];

ins.sisp.taskEnd = [...
	'Gut gemacht, diese Aufgabe ist nun vorbei. '];

ins.sisp.exampleEnd = [...
	'Gut gemacht, diese Übung ist nun vorbei. '];

% Visual WM:

ins.vwm.genInst=['In dieser Aufgabe geht es darum, sich Farben zu merken. \n'...
    'Die Bilder veranschaulichen den Ablauf der Aufgabe: \n\n'...
    '1. Fixieren Sie den Mittelpunkt des Bildschirms \n'...
    '    (ein Pfeil zeigt an, auf welche Seite Sie sich konzentrieren sollen).\n'...
    '2. Merken Sie sich die Farben auf der angezeigten Seite.\n'...
    '3. Pause. \n'...
    '4. Ist dies dieselbe Farbe an derselben Position? \n'...
    '  \n'...
    '5. Wenn dies richtig ist, drücken Sie die obere Taste "grün" (Daumen hoch).\n'...
    '    Wenn dies falsch ist, drücken Sie die untere Taste "rot" (Daumen runter). \n'...
    '    Drücken Sie "0", um zu beginnen.'];

ins.vwm.instBetween=['Bitte lesen Sie die Instruktionen nochmals sorgfältig. \n'...
    'Achten Sie insbesondere auf die Bedeutung der Tasten "grün" und "rot". \n'...
    'Die Bilder veranschaulichen den Ablauf der Aufgabe: \n\n'...
    '1. Fixieren Sie den Mittelpunkt des Bildschirms \n'...
    '    (ein Pfeil zeigt an, auf welche Seite Sie sich konzentrieren sollen).\n'...
    '2. Merken Sie sich die Farben auf der angezeigten Seite. \n'...
    '3. Pause. \n'...
    '4. Ist dies dieselbe Farbe an derselben Position? \n'...
    '  \n'...
    '5. Wenn dies richtig ist, drücken Sie die obere Taste "grün" (Daumen hoch).\n'...
    '    Wenn dies falsch ist, drücken Sie die untere Taste "rot" (Daumen runter). \n'...
    '    Drücken Sie "0", um fortzufahren.'];

ins.vwm.pause1=['Machen Sie eine kurze Pause. \n\n    '];
ins.vwm.pause2=['Machen Sie eine kurze Pause. \n\n'...
    'Wenn Sie fortfahren möchten, drücken Sie die Taste "0".'];
ins.vwm.belowThreshold=['Der erste Übungsdurchgang ist nun vorüber.\n'...
    'Gleich beginnt ein zweiter Durchgang.\n'...
    'Der Versuchleiter steht Ihnen nun für Fragen zur Verfügung.'];
    
ins.vwm.exampleEnd = [...
	'Gut gemacht, diese Übung ist nun vorbei. '];
ins.vwm.taskEnd=['Gut gemacht, diese Aufgabe ist nun zu Ende!'];
ins.vwm.nextRound=['Nun beginnt die nächste Runde!'...
    '\nBitte Platzieren Sie Ihre Finger wieder auf die Tasten "grün" und "rot".'...
    '\n\nDrücken Sie die Taste "0" um fortzufahren.'];
ins.vwm.nextRound2=['Die Runde beginnt in:'];









